spring:
  application:
    name: "Entry exam"
  datasource:
    url: jdbc:h2:mem:exam
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        transaction:
          coordinator_class: jdbc
